/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get collection tree */
        get: operations["9c3432ea36a8137917cfa407ed1663f1"];
        put?: never;
        /** Create collection */
        post: operations["71d106ce35b909a4129c4baa0d6707c9"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get collection by id */
        get: operations["63c739bae82ff04f6e91b1a6ed50975d"];
        put?: never;
        post?: never;
        /** Delete collection (soft) */
        delete: operations["ee0c1f89155f27f7d0142a8d46072830"];
        options?: never;
        head?: never;
        /** Update collection */
        patch: operations["4352077861a47d324a33fcae84432ebd"];
        trace?: never;
    };
    "/api/collections/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore deleted collection */
        post: operations["f398415cce0d2c1708623f3c5d8b542e"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collectionId}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List requests in collection */
        get: operations["a76282db056aab3f8367fdfb2b7aa9a1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List top-level requests */
        get: operations["dec429d33f7c7580b87b10b04ecfc9cc"];
        put?: never;
        /** Create request */
        post: operations["a6e46102d22269883910e187e9b85ead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get request by id */
        get: operations["5c82485fc6500a5f951751cfdfb20a8d"];
        put?: never;
        post?: never;
        /** Delete request (soft) */
        delete: operations["f50f5387d665a8378cda58568435b6bb"];
        options?: never;
        head?: never;
        /** Update request */
        patch: operations["6ee36f7103a38e627a1461a7182e620a"];
        trace?: never;
    };
    "/api/requests/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore deleted request */
        post: operations["d6cbadc0198719604a7b4da4ade24c9c"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI specification */
        get: operations["4eb615a2eab3d062f39cbd4c1c260006"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forward an HTTP request from the client sandbox */
        post: operations["1d95fde6436eb8cada030397389f5630"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get request history */
        get: operations["6a45d2ac07c1db2ed6a893e72d448b67"];
        put?: never;
        /** Record request execution */
        post: operations["ffbd3ef16fa0fa2208cc1c804c553580"];
        /** Clear all history for user */
        delete: operations["c4d40019af00f6cc573bb7fd442e0a4d"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get history entry by id */
        get: operations["7eb6221767c0aa68d7c3d05f3eb4ba0b"];
        put?: never;
        post?: never;
        /** Delete history entry */
        delete: operations["e945ee8df346875733e2346b2707d929"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["85b925b5c7def5562d1354490bb58e7d"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive a JWT */
        post: operations["28f36df7957dd2a715f8d2e73a0d94e7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["025162a66764ad7c10a26581c586d4ef"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["9fad5cc85764b48f8b48d14aec998313"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a user profile */
        put: operations["719984797ee8bb36a2679d67fe8457f2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "9c3432ea36a8137917cfa407ed1663f1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "71d106ce35b909a4129c4baa0d6707c9": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "63c739bae82ff04f6e91b1a6ed50975d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    ee0c1f89155f27f7d0142a8d46072830: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "4352077861a47d324a33fcae84432ebd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    f398415cce0d2c1708623f3c5d8b542e: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    a76282db056aab3f8367fdfb2b7aa9a1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    dec429d33f7c7580b87b10b04ecfc9cc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    a6e46102d22269883910e187e9b85ead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "5c82485fc6500a5f951751cfdfb20a8d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    f50f5387d665a8378cda58568435b6bb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "6ee36f7103a38e627a1461a7182e620a": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    d6cbadc0198719604a7b4da4ade24c9c: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "4eb615a2eab3d062f39cbd4c1c260006": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI JSON Specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    "1d95fde6436eb8cada030397389f5630": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "6a45d2ac07c1db2ed6a893e72d448b67": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    ffbd3ef16fa0fa2208cc1c804c553580: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    c4d40019af00f6cc573bb7fd442e0a4d: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "7eb6221767c0aa68d7c3d05f3eb4ba0b": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    e945ee8df346875733e2346b2707d929: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "85b925b5c7def5562d1354490bb58e7d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "28f36df7957dd2a715f8d2e73a0d94e7": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "025162a66764ad7c10a26581c586d4ef": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "9fad5cc85764b48f8b48d14aec998313": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "719984797ee8bb36a2679d67fe8457f2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
